version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    networks:
      - whisperforge_net
    depends_on:
      - transcription
      - processing
      - storage

  transcription:
    build:
      context: .
      dockerfile: services/transcription/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    networks:
      - whisperforge_net

  processing:
    build:
      context: .
      dockerfile: services/processing/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    networks:
      - whisperforge_net

  storage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    command: uvicorn services.storage.service:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    networks:
      - whisperforge_net

networks:
  whisperforge_net:
    driver: bridge

volumes:
  frontend_cache:
  audio_cache:
  processing_cache:
  storage_cache: