# Railway Configuration for WhisperForge Python App
[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production.variables]
PYTHON_VERSION = "3.11"
